## Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
      - name: cloud-gateway-app
        image: IMAGE_URL/cloud-gateway
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: "config_url"
                name: "config-cm"

---
## Ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-gateway-ingress
  annotations:
    # 구글 관리 인증서 파일을 등록한다면,
    # 아래 어노테이션 없이 빌드가 완성된 후,
    # 다시 빌드해야한다.
    kubernetes.io/ingress.allow-http: "false"
    # gke 에 생성한 전역 고정 ip
    kubernetes.io/ingress.global-static-ip-name: gateway-ip
spec:
  # HTTPS 통신 중 암호화를 담당하는 부분
  tls:
    - secretName: "msa-secret"
  rules:
  - host: "jjcode.pe.kr"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /*
        backend:
          service:
            name: cloud-gateway-svc
            # 
            port: 
              number: 433

---
## NodePort Service

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: NodePort
  selector:
    app: cloud-gateway-app
  ports:
  - port: 433
    targetPort: 9090
