---
## Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
      - name: cloud-gateway-app
        image: IMAGE_URL/cloud-gateway
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: "config_url"
                name: "config-cm"

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: test-cert
spec:
  domains:
    - jjcode.pe.kr

---
## Ingress HTTP to HTTPS redirect test 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-ingress
  annotations:
    networking.gke.io/managed-certifiactes: "test-cert"
    kubernetes.io/ingress.global-static-ip-name: cloud-gateway-static-ip
    kubernetes.io/ingress/allow-http: "false"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: jjcode.pe.kr
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /*
        backend:
          service:
            name: cloud-gateway-svc
            port: 
              number: 433

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
  # annotations:
    # cloud.google.com/app-protocols: '{"": "HTTPS"}'
spec:
  type: NodePort
  selector:
    app: cloud-gateway-app
  ports:
  - port: 433
    targetPort: 9090
