---
## Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-svc
spec:
  selector:
    matchLabels:
      app: cloud-gateway-svc
  template:
    metadata:
      labels:
        app: cloud-gateway-svc
    spec:
      containers:
      - name: cloud-gateway-svc
        image: IMAGE_URL/cloud-gateway
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm

---
## Service - LoadBalancer
# 외부 ip 노출

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway-svc
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP

---
